[versions]
agp_version = "8.12.0"
coroutines_version = "1.10.2"
kotlin_version = "2.2.0"
serialization_version = "1.9.0"
dokkatoo_version = "2.4.0"
extensions_lib_version = "16"

[libraries]
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines_version" }

kotlin-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization_version" }
kotlin-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "serialization_version" }

injekt-core = { module = "com.github.mihonapp:injekt", version = "91edab2317" }
extensions-lib = { module = "com.github.aniyomiorg:extensions-lib", version.ref = "extensions_lib_version" }
jsoup = { module = "org.jsoup:jsoup", version = "1.21.1" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.1.0" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp_version" }
dokkatoo = { id = "dev.adamko.dokkatoo", version.ref = "dokkatoo_version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }
